---
version: '3.8'

# This will run 9 COPIES of the ark server
# meaning 9 entire copies of ark server and all mods will be downloaded

x-cluster-env: &cluster-env
  CLUSTER_ID: NUGGIES
  SESSION_NAME: Dino Shaped Chicken Nuggies
  OPT_PvEAllowStructuresAtSupplyDrops: 'true'
  OPT_EnableExtraStructurePreventionVolumes: 'false'

x-mods:
  MODS: 618916953,731604991,751991809,718873660,1957185915

x-operators:
  OPERATORS: "steam64 id"

x-whitelist: &whitelist
  EXCLUSIVE_JOIN: 'true'
  WHITELIST: "steam64 ids,go,here"

x-main-node: &main-node
  MAIN_NODE: ark_island

x-container: &container
  image: ark:latest
  restart: unless-stopped
  user: 117:120
  ulimits:
    nofile:
      soft: 1000000
      hard: 1000000


services:
  ark_island:
    <<: *container
    container_name: ark_island
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: TheIsland
      OPT_Port: 7777
      OPT_QueryPort: 27015
    ports:
      - 27015:27015/udp
      - 7777:7777/udp
      - 7778:7778/udp
      - 27020:27020/tcp
    volumes:
      - ./data/the_island:/server
      - ./data:/cluster

  ark_se:
    <<: *container
    container_name: ark_se
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: ScorchedEarth_P
      OPT_Port: 7779
      OPT_QueryPort: 27016
    ports:
      - 27016:27016/udp
      - 7779:7779/udp
      - 7780:7780/udp
      - 27021:27020/tcp
    volumes:
      - ./data/scorched_earth:/server
      - ./data:/cluster

  ark_center:
    <<: *container
    container_name: ark_center
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: TheCenter
      OPT_Port: 7781
      OPT_QueryPort: 27017
    ports:
      - 27017:27017/udp
      - 7781:7781/udp
      - 7782:7782/udp
      - 27022:27020/tcp
    volumes:
      - ./data/the_center:/server
      - ./data:/cluster

  ark_rag:
    <<: *container
    container_name: ark_rag
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: Ragnarok
      OPT_Port: 7783
      OPT_QueryPort: 27018
    ports:
      - 27018:27018/udp
      - 7783:7783/udp
      - 7784:7784/udp
      - 27023:27020/tcp
    volumes:
      - ./data/ragnarok:/server
      - ./data:/cluster

  ark_aberration:
    <<: *container
    container_name: ark_aberration
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: Aberration_P
      OPT_Port: 7785
      OPT_QueryPort: 27019
    ports:
      - 27019:27019/udp
      - 7785:7785/udp
      - 7786:7786/udp
      - 27024:27020/tcp
    volumes:
      - ./data/aberration:/server
      - ./data:/cluster

  ark_extinction:
    <<: *container
    container_name: ark_extinction
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: Extinction
      OPT_Port: 7787
      OPT_QueryPort: 27020
    ports:
      - 27020:27020/udp
      - 7787:7787/udp
      - 7788:7788/udp
      - 27025:27020/tcp
    volumes:
      - ./data/extinction:/server
      - ./data:/cluster

  ark_genesis:
    <<: *container
    container_name: ark_genesis
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: Genesis
      SESSION_NAME: The Birth of Dino Shaped Chicken Nuggies
      OPT_Port: 7789
      OPT_QueryPort: 27021
    ports:
      - 27021:27021/udp
      - 7789:7789/udp
      - 7790:7790/udp
      - 27026:27020/tcp
    volumes:
      - ./data/genesis:/server
      - ./data:/cluster

  ark_val:
    <<: *container
    container_name: ark_val
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: Valguero_P
      SESSION_NAME: Foreign Dino Shaped Chicken Nuggies
      OPT_Port: 7791
      OPT_QueryPort: 27022
    ports:
      - 27022:27022/udp
      - 7791:7791/udp
      - 7792:7792/udp
      - 27027:27020/tcp
    volumes:
      - ./data/valguero:/server
      - ./data:/cluster

  ark_crystal:
    <<: *container
    container_name: ark_crystal
    environment:
      <<: *whitelist
      <<: *operators
      <<: *mods
      <<: *cluster-env
      MAP_NAME: CrystalIsles
      SESSION_NAME: Prismatic Dino Shaped Chicken Nuggies
      OPT_Port: 7793
      OPT_QueryPort: 27023
    ports:
      - 27023:27023/udp
      - 7793:7793/udp
      - 7794:7794/udp
      - 27028:27020/tcp
    volumes:
      - ./data/crystal_isles:/server
      - ./data:/cluster
